version: 2.1
orbs:
  node: circleci/node@5.2.0
jobs:
  validate:
    docker:
      - image: cimg/node:18.6.0
    steps:
      - run: node --version
      - run: yarn versions
      - checkout
      - run: yarn install
      - run: yarn validate
workflows:
  version: 2
  validate:
    jobs:
      - validate
